#!/usr/bin/bash

# "@" é um array de argumentos($1,$2...), e o ':' representa o argumento -1 (último argumento)
# "@" is an array of arguments($1,$2...), and ':' represents this argument at -1 (last argument)
ULTI="${@: -1}"

if [[ -z "$1" ]] || [[ "$1" == "-h" ]]; then
  echo -e "\n./${0##*/} <URL> <-s OR -ns> \"php|jpeg|txt|jpg|svg\"\n\
     -h        :: Show the help menu\n\
     -s        :: Include subdomains\n\
     -ns       :: Not including subdomains\n\
     \"png|jpg\" :: Exclude file extensions ( Separete using \"|\" (pipe) )\n"
#https://index.commoncrawl.org/CC-MAIN-2022-05-index?url=$1/*&output=json" | jq '.url'
fi

# Primeira etapa sem crawling de subdominios
# First phase without subdomain crawling
if [[ "$2" == "-ns" ]] && [[ ! -z "$1" ]]; then
  curl -s -k --tcp-fastopen --tcp-nodelay "https://web.archive.org/cdx/search/cdx?url=$1/*&output=json&fl=original&collapse=urlkey&page=/" | tr -d '[',']','"' | egrep ".*?:\/\/.*\?.*\=[^$]" | egrep -v ".($ULTI)" | uniq
  curl -s -k --tcp-fastopen --tcp-nodelay "https://index.commoncrawl.org/CC-MAIN-2022-05-index?url=$1/*&output=json&fl=url&page=0" | jq '.url' | tr -d '"' | egrep ".*?:\/\/.*\?.*\=[^$]" | uniq
  exit 0
# Segunda etapa com crawling de subdominios
# Second phase with subdomain crawling
elif [[ "$2" == "-s" ]] && [[ ! -z "$1" ]]; then
  #curl -s -k --tcp-fastopen --tcp-nodelay --connect-timeout 25 "https://web.archive.org/cdx/search/cdx?url=*.$1/*&output=json&fl=original&collapse=urlkey&page=/" | tr -d '[',']','"' | egrep ".*?:\/\/.*\?.*\=[^$]" | egrep -v ".($ULTI)" | uniq
  curl -s -k --tcp-fastopen --tcp-nodelay "https://web.archive.org/cdx/search/cdx?url=*.$1/*&output=json&fl=original&collapse=urlkey&page=/" | tr -d '[',']','"' | egrep ".*?:\/\/.*\?.*\=[^$]" | egrep -v ".($ULTI)" | uniq
  curl -s -k --tcp-fastopen --tcp-nodelay "https://index.commoncrawl.org/CC-MAIN-2022-05-index?url=*.$1/*&output=json&fl=url&page=0" | jq '.url' | tr -d '"' | egrep ".*?:\/\/.*\?.*\=[^$]" | uniq
  exit 0
fi
